name: 创建新任务
description: 创建一个新的开源实习生主题任务
title: "[任务]: "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        遵循此模板来创建一个新的开源实习生任务。请确保下述表单项目已详尽的描述了一个具体的任务。
        请注意：

        1. 任务的描述应当是确切的。请避免创建实际内容模糊且宽泛的任务。
        2. 任务的最终产出除了使实习生能通过任务本身获得成长之外，也应当对 deepin 开源社区有所益处。
        3. 应当尽可能详尽的提供必要的文档步骤（可以放置在 Wiki 等位置）。
  - type: dropdown
    id: task-difficuty
    attributes:
      label: 这个任务的难度是？
      options:
        - 普通任务
        - 进阶任务
        - 高级任务
    validations:
      required: true
  - type: textarea
    id: task-description
    attributes:
      label: 任务描述
      description: 请描述此任务。任务描述的用语需要清晰明了，便于实习生准确理解。
      placeholder: |
        （示例仅供参考，可视情况任意调整文字内容：）
        基于 DTK，完成一个可以 XXXXXXX 的 DDE 桌面小部件插件。

        此应用程序应当满足：

        1. 应当 XXXXXXX
        2. 应当能够 XXXXXXXX
        3. XXXXXXXX

        此任务 XXXXXXX，XXXXXXXXX，XXXXXXXXX。
    validations:
      required: true
  - type: textarea
    id: task-setup
    attributes:
      label: 环境的准备
      description: 实习生若要完成此任务，应当如何准备相关的工作/开发环境？
      placeholder: |
        （示例仅供参考，可视情况任意调整文字内容：）
        完成此任务需要您 XXXXXXXXX。为方便起见，下述步骤假定您在使用 XXX 发行版并使用 XXX 环境。

        - 首先安装相应的开发环境：`apt install xxxxxx`
        - 进行如下配置：XXXXXXX
        - 进行如下步骤：XXXXXX

        额外的，您可能还需要 XXXXXXXX，相关的详细步骤说明也可以参阅 [编写 XXX 的说明](https://wiki.deepin.org/页面标题)，XXXX。
    validations:
      required: true
  - type: textarea
    id: task-requirement
    attributes:
      label: 验收标准
      description: 请描述对任务的具体要求/验收标准。该项用于评估实习生任务完成是否达标，是检验标准，检验标准需能经推敲和不被质疑。
      placeholder: |
        （示例仅供参考，可视情况任意调整文字内容：）
        最终完成的应用程序应当能够提供下述功能：

        - [ ] 能够恰当的运行和退出（必须满足）
        - [ ] 提供 XXXXXX 功能（必须满足）
        - [ ] 能够 XXXXXXXX
        - [ ] 在 deepin-community 进行正常的打包
        - [ ] XXXXXXXXX

        我们通过对上述各项标准的完成数量来评估任务的完成程度
    validations:
      required: true
  - type: textarea
    id: contribute-to
    attributes:
      label: 涉及的项目/提交到何处
      description: 描述此任务所涉及到的项目，告诉参与者应当将贡献提交到什么位置，例如具体哪个/些仓库或者哪个/些平台。
      placeholder: |
        （示例仅供参考，可视情况任意调整文字内容：）
        - 此项目需要您将代码提交到 XXXXXXX 仓库之中
        - 对于 XXXX 的开发，可以直接在您自己的帐号下新建仓库进行开发。
        - 对于软件的打包，需要在 [deepin-community](https://github.com/deepin-community) 组织下申请创建仓库并在对应的仓库中进行开发，具体步骤参见[XXXX](https://wiki.deepin.org/相关的页面)
        - 您需要将文档提交到 XXXXXX
        - XXXXX
    validations:
      required: true
  - type: textarea
    id: task-documentation
    attributes:
      label: 参考文档
      description: 请提供任务过程所涉及到的事项所对应的参考资料与文档。
      placeholder: |
        （示例仅供参考，可视情况任意调整文字内容：）
        - [DTK 文档](#)
        - [如何在 deepin-community 创建软件包](#)
        - [创建 Wiki 页面的注意事项](#)
        - ...
  - type: textarea
    id: task-mentors
    attributes:
      label: 联系方式
      description: 请提供任务相关导师的交流/联系方式。
      placeholder: |
        （示例仅供参考，可视情况任意调整文字内容：）
        此任务的导师为： @mentor @another_mentor
        您也可以添加导师的微信/QQ/Matrix/Telegram/etc：XXXXXXX
        相关讨论群：XXXXXXX

        此外，您也可以在 XXXX 创建讨论主题来进行交流。
        如果在过程中，您发现了与此任务本身无关的 deepin 缺陷，也可以在 XXX 进行讨论。
